# Generated by Django 5.1.7 on 2025-04-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_invoice_status_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='previous_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
