# Generated by Django 5.1.7 on 2025-04-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('invoice_created', 'Invoice Created'), ('invoice_updated', 'Invoice Updated'), ('invoice_deleted', 'Invoice Deleted'), ('customer_added', 'Customer Added'), ('customer_updated', 'Customer Updated'), ('customer_deleted', 'Customer Deleted'), ('payment_initiated', 'Payment Initiated'), ('payment_approved', 'Payment Approved'), ('payment_rejected', 'Payment Rejected'), ('status_changed', 'Status Changed')], max_length=20),
        ),
    ]
