# Generated by Django 5.1.7 on 2025-03-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('carrier', 'Carrier'), ('customer', 'Customer')], default='customer', max_length=10),
        ),
    ]
